In [2]:
import numpy as np

def rotate_rings(matrix):
    n = len(matrix)
    rotated = matrix.copy()

    # For each ring level, starting from outermost
    for ring in range(n // 2):
        # Store the positions we need to rotate
        positions = []

        # Top row
        for j in range(ring, n-ring-1):
            positions.append((ring, j))

        # Right column
        for i in range(ring, n-ring-1):
            positions.append((i, n-ring-1))

        # Bottom row
        for j in range(n-ring-1, ring, -1):
            positions.append((n-ring-1, j))

        # Left column
        for i in range(n-ring-1, ring, -1):
            positions.append((i, ring))

        # Perform the rotation
        values = [matrix[pos[0]][pos[1]] for pos in positions]
        values = [values[-1]] + values[:-1]  # Rotate one position

        # Update the values in rotated matrix
        for (pos, val) in zip(positions, values):
            rotated[pos[0]][pos[1]] = val

    return rotated

# 1. Create random array
n = 5  # Size of the array (you can change this)
original = np.random.randint(0, 100, size=(n, n))

# Print original array
print("Original array:")
print(original)

# 2. & 3. Rotate and print result
rotated = rotate_rings(original)
print("\nRotated array:")
print(rotated)

Original array:
[[12 68 58 45 75]
 [57  2 28 29 62]
 [59 65 96 48 45]
 [92 35 38 75 87]
 [89 48 69 46 12]]

Rotated array:
[[57 12 68 58 45]
 [59 65  2 28 75]
 [92 35 96 29 62]
 [89 38 75 48 45]
 [48 69 46 12 87]]
